### ISSUE TITLE
Gender color outline in SVG not working in AI and Inkscape

### ISSUE THREAD

**Issue by FelixBuehler** [magicsunday/webtrees-fan-chart#101]
**Describe the bug**
When exporting the SVG, my programs won't display the color of the gender-outline. This is most like due to the color being a variable and not set in the path.

**Expected behavior**
All normal programs to be able to deal with the color.

**Screenshots**
(Additional info removed by me)
![Screenshot 2024-01-22 173158](https://github.com/magicsunday/webtrees-fan-chart/assets/51091213/f214764d-19eb-43d8-97f8-0ee3f7d72437)

**Comment by magicsunday** [comment]
Looks like Inkscape is not able to handle CSS variables. Adding a style tag directly to a path-element `style="fill: var(--sex-f-bg, rgb(233, 218, 241))` does not change anything, only if I remove the "var" part from it.

So we need to find a way to extract all used CSS classes of the chart, look up any CSS variable and replace it with the proper defined color expression, create a new style-tag inside exported SVG containing all the corrected CSS.

**Comment by FelixBuehler** [comment]
A small workaround I do now: I open the exported svg in my browser and then print it as pdf. Then it contains all the colors and is even faster to view than the SVG. I'm no expert (in this field), so maybe a "export to PDF" might even be the best solution, since it's the file format most people can handle?

**Comment by magicsunday** [comment]
Exported as SVG

![fan-chart](https://github.com/user-attachments/assets/97ef19a7-b958-42fe-abfd-e9a748862485)

**Comment by FelixBuehler** [comment]
Awesome! That looks very good. Do the failed checks of the commit prevent this changes to be accepted? I'm no expert in Git-Checks/Commits/PR.

**Comment by magicsunday** [comment]
I will merge it tomorrow into the main branch.
