### ISSUE TITLE
After upgrading, the Chinese surname and first name are reversed

### ISSUE THREAD

**Issue by iyoua** [magicsunday/webtrees-fan-chart#102]
After upgrading the module to 2.7.0, there was an issue with the display of Chinese names, which should be restored to the correct style displayed in 2.6.2.
![fan-chart](https://github.com/magicsunday/webtrees-fan-chart/assets/102014216/5c14f8df-d341-4ba7-bddf-dae9a7549182)
The above image shows an error display of 2.7.0,The following image is the correct display of 2.6.2.
![fan-chart (1)](https://github.com/magicsunday/webtrees-fan-chart/assets/102014216/fff1a11c-ea51-4a74-8259-78b9a23f293b)

**Comment by magicsunday** [comment]
@iyoua Should be fixed in latest version of branch 2.1. Could you please test it?
