### ISSUE TITLE
Question about display fan

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-fan-chart#104]
in version 2.6.2 if I have a person whose gedcom is :

1 NAME Anne* Agnès /DUPON/
2 GIVN Anne Agnès
2 SURN DUPONT DUPON

the display of his name in the fan is:
Anne Agnès DUPON

but in 2.7.0 the display becomes :
Anne Agnès DUPONT DUPON

to display as in 2.6.2, I had to modify the gedcom as follows

1 NAME Anne* Agnès /DUPON/
2 GIVN Anne Agnès
2 SURN DUPON , DUPONT

in 2 SURN
you can display the evolution of the writing of the surname without commas

in 1 NAME between the / it's the name at birth or marriage ...

we should be working with NAME and not SURN

thanks for your help to keep the same display as in 2.6.2

**Comment by HRN65** [comment]
In gedcom different (spelling of) names can be added separated by comma for indexing purpose.

1 NAME Aaaaa /Xxxxx/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN Xxxxx, Xxxxy

Recently, there has been changes in pedigree-, descendants- and fan-charts, and names are now displayed differently in those charts.

In example above, Aaaaa Xxxxx (1 NAME) is the name that should be displayed.

In fan chart the name Aaaaa, Aaaab, Aaaac Xxxxx is displayed.
In pedigree and descendants chart only Xxxxx is displayed. Given name is missing

If there is 1 NAME only, with no subtags, the name is correctly displayed Aaaaa Xxxxx
1 NAME Aaaaa /Xxxxx/

If there is no name, the layout og both pedigree and descendants chart is broken
Fanchart is displayed correctly with name ... ...

**Comment by Fa10175** [comment]
in gedcom i have :
1 NAME **Aaaab** /**Xxxxy**/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN Xxxxx, Xxxxy

in fachart how is the display?

Aaaab Xxxxy
or
Aaaaa Xxxxx

**Comment by HRN65** [comment]
Testing your gedcom
 
1 NAME Aaaaa /Xxxxy/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN Xxxxx, Xxxxy

The name Aaaaa, Aaaab, Aaaac Xxxxx is displayed in fan chart (would have expected the name Aaaaa Xxxxy)
In pedigree and descendant charts the layout is broken

**Comment by Fa10175** [comment]
you must always have in 
1 NAME between / 
first in 
2 SURN

this is therefore more valid
1 NAME Aaaaa /XxxxZ/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN XxxxX, XxxxY, XxxxZ

and must be changed to 
1 NAME Aaaaa /XxxxZ/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN XxxxZ, XxxxX, XxxxY
?
and 
1 NAME Aaaaa /XxxxY/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN XxxxX, XxxxY, XxxxZ

and must be changed to 
1 NAME Aaaaa /XxxxY/
2 GIVN Aaaaa, Aaaab, Aaaac
2 SURN XxxxY, XxxxX, XxxxZ
?
that's a lot of work.

in 2.6.2 it was simpler

**Comment by magicsunday** [comment]
Could you please test with the latest version from branch 2.1, if this fixes your issues?

**Comment by Fa10175** [comment]
I download webtrees-fan-chart-master.zip from git but i have this error:

Fatal error in module: webtrees-fan-chart
Error: Call to undefined method Fisharebest\Webtrees\Registry::container()
in ......\webtrees\modules_v4\webtrees-fan-chart\module.php:25 Stack trace:
#0 ......\webtrees\app\Services\ModuleService.php(735): include() #1
......\webtrees\app\Services\ModuleService.php(709):
Fisharebest\Webtrees\Services\ModuleService::load('C:\\Users\\JL-R\\D...')
#2 [internal function]:
Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('C:\\Users\\JL-R\\D...',
17) #3 ......\webtrees\vendor\illuminate\collections\Collection.php(695):
array_map(Object(Closure), Array, Array) #4
......\webtrees\app\Services\ModuleService.php(708):
Illuminate\Support\Collection->map(Object(Closure)) #5
......\webtrees\app\Services\ModuleService.php(630):
Fisharebest\Webtrees\Services\ModuleService->customModules() #6
......\webtrees\app\Cache.php(58):
Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}()
#7 ......\webtrees\vendor\symfony\cache\Adapter\ArrayAdapter.php(84):
Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem),
true) #8 ......\webtrees\app\Cache.php(55):
Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...',
Object(Closure)) #9 ......\webtrees\app\Services\ModuleService.php(620):
Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) #10
......\webtrees\app\Services\ModuleService.php(581):
Fisharebest\Webtrees\Services\ModuleService->all(true) #11
......\webtrees\app\Http\Middleware\UseLanguage.php(82):
Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...',
true) #12 ......\webtrees\app\Http\Middleware\UseLanguage.php(61):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest))
#13 ......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #14
......\webtrees\app\Http\Middleware\UseSession.php(78):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #16
......\webtrees\app\Http\Middleware\UpdateDatabaseSchema.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #18
......\webtrees\app\Http\Middleware\UseDatabase.php(122):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #20
......\webtrees\app\Http\Middleware\BadBotBlocker.php(308):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #22
......\webtrees\app\Http\Middleware\CompressResponse.php(71):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #24
......\webtrees\app\Http\Middleware\ContentLength.php(40):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #26
......\webtrees\vendor\middlewares\client-ip\src\ClientIp.php(65):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27
......\webtrees\app\Http\Middleware\ClientIp.php(47):
Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #28
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #29
......\webtrees\app\Http\Middleware\HandleExceptions.php(89):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #31
......\webtrees\app\Http\Middleware\BaseUrl.php(73):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #33
......\webtrees\app\Http\Middleware\ReadConfigIni.php(68):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #35
......\webtrees\app\Http\Middleware\SecurityHeaders.php(48):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #37
......\webtrees\app\Http\Middleware\EmitResponse.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #39
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40
......\webtrees\app\Webtrees.php(275):
Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #41
......\webtrees\app\Webtrees.php(262):
Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest),
Array) #42 ......\webtrees\index.php(51):
Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}
Fatal error in module: webtrees-fan-chart
Error: Call to undefined method Fisharebest\Webtrees\Registry::container()
in ......\webtrees\modules_v4\webtrees-fan-chart\module.php:25 Stack trace:
#0 ......\webtrees\app\Services\ModuleService.php(735): include() #1
......\webtrees\app\Services\ModuleService.php(709):
Fisharebest\Webtrees\Services\ModuleService::load('C:\\Users\\JL-R\\D...')
#2 [internal function]:
Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('C:\\Users\\JL-R\\D...',
17) #3 ......\webtrees\vendor\illuminate\collections\Collection.php(695):
array_map(Object(Closure), Array, Array) #4
......\webtrees\app\Services\ModuleService.php(708):
Illuminate\Support\Collection->map(Object(Closure)) #5
......\webtrees\app\Services\ModuleService.php(630):
Fisharebest\Webtrees\Services\ModuleService->customModules() #6
......\webtrees\app\Cache.php(58):
Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}()
#7 ......\webtrees\vendor\symfony\cache\Adapter\ArrayAdapter.php(84):
Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem),
true) #8 ......\webtrees\app\Cache.php(55):
Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...',
Object(Closure)) #9 ......\webtrees\app\Services\ModuleService.php(620):
Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) #10
......\webtrees\app\Services\ModuleService.php(581):
Fisharebest\Webtrees\Services\ModuleService->all(true) #11
......\webtrees\app\Http\Middleware\UseLanguage.php(82):
Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...',
true) #12 ......\webtrees\app\Http\Middleware\UseLanguage.php(61):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest))
#13 ......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #14
......\webtrees\app\Http\Middleware\UseSession.php(78):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #16
......\webtrees\app\Http\Middleware\UpdateDatabaseSchema.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #18
......\webtrees\app\Http\Middleware\UseDatabase.php(122):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #20
......\webtrees\app\Http\Middleware\BadBotBlocker.php(308):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #22
......\webtrees\app\Http\Middleware\CompressResponse.php(71):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #24
......\webtrees\app\Http\Middleware\ContentLength.php(40):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #26
......\webtrees\vendor\middlewares\client-ip\src\ClientIp.php(65):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27
......\webtrees\app\Http\Middleware\ClientIp.php(47):
Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #28
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #29
......\webtrees\app\Http\Middleware\HandleExceptions.php(89):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #31
......\webtrees\app\Http\Middleware\BaseUrl.php(73):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #33
......\webtrees\app\Http\Middleware\ReadConfigIni.php(68):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #35
......\webtrees\app\Http\Middleware\SecurityHeaders.php(48):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #37
......\webtrees\app\Http\Middleware\EmitResponse.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #39
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40
......\webtrees\app\Webtrees.php(275):
Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #41
......\webtrees\app\Webtrees.php(262):
Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest),
Array) #42 ......\webtrees\index.php(51):
Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}
Fatal error in module: webtrees-fan-chart
Error: Call to undefined method Fisharebest\Webtrees\Registry::container()
in ......\webtrees\modules_v4\webtrees-fan-chart\module.php:25 Stack trace:
#0 ......\webtrees\app\Services\ModuleService.php(735): include() #1
......\webtrees\app\Services\ModuleService.php(709):
Fisharebest\Webtrees\Services\ModuleService::load('C:\\Users\\JL-R\\D...')
#2 [internal function]:
Fisharebest\Webtrees\Services\ModuleService::Fisharebest\Webtrees\Services\{closure}('C:\\Users\\JL-R\\D...',
17) #3 ......\webtrees\vendor\illuminate\collections\Collection.php(695):
array_map(Object(Closure), Array, Array) #4
......\webtrees\app\Services\ModuleService.php(708):
Illuminate\Support\Collection->map(Object(Closure)) #5
......\webtrees\app\Services\ModuleService.php(630):
Fisharebest\Webtrees\Services\ModuleService->customModules() #6
......\webtrees\app\Cache.php(58):
Fisharebest\Webtrees\Services\ModuleService->Fisharebest\Webtrees\Services\{closure}()
#7 ......\webtrees\vendor\symfony\cache\Adapter\ArrayAdapter.php(84):
Fisharebest\Webtrees\Cache::Fisharebest\Webtrees\{closure}(Object(Symfony\Component\Cache\CacheItem),
true) #8 ......\webtrees\app\Cache.php(55):
Symfony\Component\Cache\Adapter\ArrayAdapter->get('372b64b23390f9d...',
Object(Closure)) #9 ......\webtrees\app\Services\ModuleService.php(620):
Fisharebest\Webtrees\Cache->remember('all-modules', Object(Closure)) #10
......\webtrees\app\Services\ModuleService.php(581):
Fisharebest\Webtrees\Services\ModuleService->all(true) #11
......\webtrees\app\Http\Middleware\UseLanguage.php(82):
Fisharebest\Webtrees\Services\ModuleService->findByInterface('Fisharebest\\Web...',
true) #12 ......\webtrees\app\Http\Middleware\UseLanguage.php(61):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->languages(Object(Nyholm\Psr7\ServerRequest))
#13 ......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseLanguage->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #14
......\webtrees\app\Http\Middleware\UseSession.php(78):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #15
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseSession->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #16
......\webtrees\app\Http\Middleware\UpdateDatabaseSchema.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #17
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UpdateDatabaseSchema->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #18
......\webtrees\app\Http\Middleware\UseDatabase.php(122):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #19
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\UseDatabase->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #20
......\webtrees\app\Http\Middleware\BadBotBlocker.php(308):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #21
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BadBotBlocker->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #22
......\webtrees\app\Http\Middleware\CompressResponse.php(71):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #23
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\CompressResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #24
......\webtrees\app\Http\Middleware\ContentLength.php(40):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #25
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ContentLength->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #26
......\webtrees\vendor\middlewares\client-ip\src\ClientIp.php(65):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #27
......\webtrees\app\Http\Middleware\ClientIp.php(47):
Middlewares\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #28
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ClientIp->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #29
......\webtrees\app\Http\Middleware\HandleExceptions.php(89):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #30
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\HandleExceptions->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #31
......\webtrees\app\Http\Middleware\BaseUrl.php(73):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #32
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\BaseUrl->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #33
......\webtrees\app\Http\Middleware\ReadConfigIni.php(68):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #34
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\ReadConfigIni->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #35
......\webtrees\app\Http\Middleware\SecurityHeaders.php(48):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #36
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\SecurityHeaders->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #37
......\webtrees\app\Http\Middleware\EmitResponse.php(57):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #38
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(136):
Fisharebest\Webtrees\Http\Middleware\EmitResponse->process(Object(Nyholm\Psr7\ServerRequest),
Object(Middleland\Dispatcher)) #39
......\webtrees\vendor\oscarotero\middleland\src\Dispatcher.php(118):
Middleland\Dispatcher->handle(Object(Nyholm\Psr7\ServerRequest)) #40
......\webtrees\app\Webtrees.php(275):
Middleland\Dispatcher->dispatch(Object(Nyholm\Psr7\ServerRequest)) #41
......\webtrees\app\Webtrees.php(262):
Fisharebest\Webtrees\Webtrees::dispatch(Object(Nyholm\Psr7\ServerRequest),
Array) #42 ......\webtrees\index.php(51):
Fisharebest\Webtrees\Webtrees->httpRequest() #43 {main}

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 2 avr. 2024 à 14:56, Rico Sonntag ***@***.***> a
écrit :

**Comment by Fa10175** [comment]
same with webtrees-pedigree-chart-master.zip and
webtrees-descendants-chart-main.zip



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by magicsunday** [comment]
@Fa10175 

Not the master/main branch, as this one is the current development branch for webtrees 2.2, Use the version from branch 2.1 => https://github.com/magicsunday/webtrees-fan-chart/tree/2.1 => https://github.com/magicsunday/webtrees-fan-chart/archive/refs/heads/2.1.zip

**Comment by Fa10175** [comment]
@Rico Sonntag

I test yours Fan-chart , pedigree-chart and descendants-chart in 2.1 last
version.
I haven't seen any problems even with SURN list comma or without comma.
Thanks

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Sans
virus.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le mar. 2 avr. 2024 à 18:38, Rico Sonntag ***@***.***> a
écrit :
