### ISSUE TITLE
Missing Surname prefix in diagram

### ISSUE THREAD

**Issue by ArnoS57** [magicsunday/webtrees-fan-chart#106]
Hi,

I'm missing the "Surname prefix" in the diagrams.
Is this a bug or can it be a new feature?

I'm missing it also in your other addons.

Arno

**Comment by magicsunday** [comment]
What version do you use?

**Comment by ArnoS57** [comment]
Hi,

I use: Webtrees 2.1.20 with Fanchart 2.7.0, Descendantschart 1.8.1 and
Pedigreechart 1.7.1

Met vriendelijke groet, Arno Sormani Verzonden via mijn Ipad/Iphone


Op zo 21 apr 2024 om 21:25 schreef Rico Sonntag ***@***.***>

**Comment by magicsunday** [comment]
Can you please try the latest version from branch 2.1 (https://github.com/magicsunday/webtrees-fan-chart/tree/2.1), whether your problem persists?

Seems like the same problem as https://github.com/magicsunday/webtrees-fan-chart/issues/104

**Comment by ArnoS57** [comment]
Hi Rick,

Fan-chart 2.1 works fine the surname prefix is now shown.
