### ISSUE TITLE
Names of individuals

### ISSUE THREAD

**Issue by jpretired** [magicsunday/webtrees-fan-chart#107]
**Describe the bug**
Names of individuals in fanchart used to be (before 2.7.0) taken from tag NAME. Now they seem to be taken from GIVEN and SURNAME which is incorrect.

**To Reproduce**
Display fanchart of any female individual:
https://jprodina.cz/tree/nase-rodina/webtrees-fan-chart/I46
**Expected behavior**
Names to be taken from tag NAME.

**Screenshots**
![image](https://github.com/user-attachments/assets/f0ff4899-5be9-446c-92a3-078e225a2f77)

![image](https://github.com/user-attachments/assets/37b2ac8c-eff6-463e-99a2-5628c754a64c)

**Desktop (please complete the following information):**
 - Browser Firefox and others
 - Webtrees version 2.1.20
 - Version of fan chart 2.7.0

**Comment by magicsunday** [comment]
(?) Why is separate surname not the same as in the "NAME" tag?

**Comment by jpretired** [comment]
Because in my language (Czech) the feminine surnames are inflected (gender inflection).
Btw your previous image shows the state when I downgraded back to 2.6.2. Now I updated to 2.7.0 so you can try the link again.

**Comment by magicsunday** [comment]
Can you please try the latest version from branch 2.1?

**Comment by jpretired** [comment]
What modules should I download from branch 2.1?

**Comment by jpretired** [comment]
Thank you.
Now with branch 2.1:
![image](https://github.com/user-attachments/assets/719204b2-c7c8-43be-91cb-c34c18ce7165)

The chart is OK:
![image](https://github.com/user-attachments/assets/6f6b9e21-db82-4fe4-996f-6d5107014813)

May I keep this version running on my website?

**Comment by magicsunday** [comment]
Yes, of course, that should work without any problems.
