### ISSUE TITLE
Add marriage dates

### ISSUE THREAD

**Issue by marku5** [magicsunday/webtrees-fan-chart#12]
Hello Rico,

another idea (seen on webpages of another genealogy-SW PRO-GEN: http://www.pro-gen.nl/pg-d.pdf) is to add the marriage dates inbetween.

Regards, Markus

**Comment by marku5** [comment]
Hi Rico,
What's your opinion about this idea?
Viele Grüße
Markus

**Comment by marku5** [comment]
Hello Rico,
Could you please comment on this suggestion...or close this issue if it doesn‘t fit to your plans. Thanks!
VG Markus

**Comment by magicsunday** [comment]
Hi, 

I'm sorry your case has been on for so long. In the "dev" branch (https://github.com/magicsunday/webtrees-fan-chart/tree/dev) I tinkered something that looks similar to your template. See if it's going in the right direction. All of this is still very rudimentary and e.g. for the start person, the display is still postponed.

**Comment by SodanWT** [comment]
Hi, I'm also interested by this evolution. I tried the dev version, I think it is nearly good, just 2 things:
1) This should be an option: I really like having marriage dates, but I also really like not having them, it depends what I want to do with the chart at the time (presentation to family, chart to help figure out what's missing...)
2) There is a little bug with the first marriage date, it is upside down (see the screenshot). Maybe that's what you meant by "for the start person, the display is still postponed."
![first marriage date upside down](https://user-images.githubusercontent.com/13674759/118379124-ca81ce00-b5d8-11eb-8363-4650983ebcf0.png)
Regards
