### ISSUE TITLE
Download button

### ISSUE THREAD

**Issue by Amgine0** [magicsunday/webtrees-fan-chart#19]
It would be useful to (optional configurable) have a download button, so an individual svg chart might be saved for other use.

**Comment by magicsunday** [comment]
Do you mean saving the SVG as an image?

**Comment by Amgine0** [comment]
Yes, as a .svg downloadable file.

**Comment by Gunnar-GO** [comment]
you could extract the SVG from source code.

but since Font is defined by theme, background some other too, it wouldn't be complete / the same.

**Comment by Ziris85** [comment]
I would like to second this feature request of having the ability to export/print this view to PDF/SVG/JPG/etc. This is probably one of my favorite ways of visualizing my tree and it looks stunning on my site, but when I try to print the page to PDF or straight to my printer, it ends up as either an unreadable blurry mess, or readable but out of bounds for a single page (for context, I'm trying to view 7 or 8 generations back).

**Comment by Ziris85** [comment]
> Added export of chart as PNG and SVG

Yes! This works perfectly. Thank you for adding this feature!
