### ISSUE TITLE
Display detail person on windows

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-fan-chart#21]
First thanks to your job.
It is possible to have on future something like 

![image](https://user-images.githubusercontent.com/10681601/48977126-c2461900-f094-11e8-9e3b-baa94243da82.png)

when we select a person.
Thanks

**Comment by magicsunday** [comment]
In you Perform a Right click on an individual you are Now Opening an Overlay with individual image and birth/death/marriage Dates. Not Workong on mobile devices.
