### ISSUE TITLE
PDF export functionality

### ISSUE THREAD

**Issue by ekdahl** [magicsunday/webtrees-fan-chart#26]
It would be really useful to have a button that creates a PDF file with a chart that fills the whole page with small margins. Page size could be selected, like A3 or A4. I've come to the conclusion that a 225° chart is optimal to utilize as much space as possible of an Ax proportioned page. It would save the hassle of exporting the SVG and later printing it to PDF and then cropping the PDF before printing it.

**Comment by ekdahl** [comment]
Maybe a more feasible solution would be an option to show only the chart with a minimum bounding box (so the chart can fill the whole page), for example in a new browser tab. That would then be easy to print to a printer or PDF printer.
The problem now is that there is a header that is included when printing, and the bounding box is larger than the chart, so it needs to be cropped later.

**Comment by Gunnar-GO** [comment]
Actually if you print the page it scales through the left and right border. Your webpage-scale may influence this too. It's only a header and the chart.

Most systems and browser can virtually print and save as pdf.
// sadly it isn't saved as vectors but in a readable resolution, at least in chrome.

**Comment by magicsunday** [comment]
SVG => PDF seems not that easy

- https://github.com/yWorks/svg2pdf.js/
- https://github.com/CBiX/svgToPdf.js/
- https://github.com/alafr/SVG-to-PDFKit

**Comment by ekdahl** [comment]
A possibility to save the SVG as a self-contained file (not dependant on css etc.) would work just as well, I suppose. I've tried lots of different plugins for Chrome for saving SVG files from web pages but none of them works completely. There's always something missing, like background colors or font information.

**Comment by magicsunday** [comment]
With https://github.com/magicsunday/webtrees-fan-chart/commit/b3c260e0cd1bb9cfae02564ba1bac1015cb690bf I added an export as PNG as PDF is a bit more to do. The image size measures A4 at 300 DPI/PPI.

**Comment by ekdahl** [comment]
Great! Thanks a lot. That should satisfy the export needs just fine, as long as the resolution is enough. Just need to upgrade to webtrees 2.0 to be able to test then.

**Comment by ekdahl** [comment]
I've tested the new functionality now and it's great! Found no issues.
