### ISSUE TITLE
Undefined options

### ISSUE THREAD

**Issue by curtisdelicata** [magicsunday/webtrees-fan-chart#28]
ErrorException: Undefined variable: options in file /resources/views/components/select.phtml on line 19
Stack trace:
  1. ErrorException->() /resources/views/components/select.phtml:19
  2. Fisharebest\Webtrees\Webtrees->Fisharebest\Webtrees\{closure}() /resources/views/components/select.phtml:19
  3. include() /app/View.php:190
  4. Fisharebest\Webtrees\View->render() /app/View.php:284
  5. Fisharebest\Webtrees\View->make() /app/Helpers/functions.php:108
  6. view() /modules_v4/webtrees-fan-chart/resources/views/chart.phtml:54
  7. include() /app/View.php:190
  8. Fisharebest\Webtrees\View->render() /app/View.php:284
  9. Fisharebest\Webtrees\View->make() /app/Helpers/functions.php:108
 10. view() /app/Module/AbstractModule.php:257
 11. Fisharebest\Webtrees\Module\AbstractModule->viewResponse() /modules_v4/webtrees-fan-chart/src/Module.php:90
 12. MagicSunday\Webtrees\FanChart\Module->getChartAction() [internal]:0
 13. ReflectionMethod->invoke() /app/Application.php:45
 14. Fisharebest\Webtrees\Application->dispatch() /app/Http/Controllers/ModuleController.php:82
 15. Fisharebest\Webtrees\Http\Controllers\ModuleController->action() [internal]:0
 16. ReflectionMethod->invoke() /app/Application.php:45
 17. Fisharebest\Webtrees\Application->dispatch() /index.php:156
 18. {closure}() /app/Module/HitCountFooterModule.php:185
 19. Fisharebest\Webtrees\Module\HitCountFooterModule->handle() /index.php:142
 20. {closure}() /app/Http/Middleware/CheckCsrf.php:64
 21. Fisharebest\Webtrees\Http\Middleware\CheckCsrf->handle() /index.php:142
 22. {closure}() /app/Http/Middleware/UseTransaction.php:43
 23. Fisharebest\Webtrees\Http\Middleware\UseTransaction->handle() /index.php:142
 24. {closure}() /app/Http/Middleware/Housekeeping.php:75
 25. Fisharebest\Webtrees\Http\Middleware\Housekeeping->handle() /index.php:142
 26. {closure}() /app/Http/Middleware/DebugBarData.php:42
 27. Fisharebest\Webtrees\Http\Middleware\DebugBarData->handle() /index.php:142
 28. {closure}() /app/Http/Middleware/BootModules.php:59
 29. Fisharebest\Webtrees\Http\Middleware\BootModules->handle() /index.php:142
 30. {closure}() /app/Http/Middleware/UseTheme.php:71
 31. Fisharebest\Webtrees\Http\Middleware\UseTheme->handle() /index.php:142
 32. {closure}() /app/Http/Middleware/UseLocale.php:52
 33. Fisharebest\Webtrees\Http\Middleware\UseLocale->handle() /index.php:142
 34. {closure}() /app/Http/Middleware/UseTree.php:58
 35. Fisharebest\Webtrees\Http\Middleware\UseTree->handle() /index.php:142
 36. {closure}() /app/Http/Middleware/UseSession.php:59
 37. Fisharebest\Webtrees\Http\Middleware\UseSession->handle() /index.php:142
 38. {closure}() /app/Http/Middleware/UseFilesystem.php:50
 39. Fisharebest\Webtrees\Http\Middleware\UseFilesystem->handle() /index.php:142
 40. {closure}() /app/Http/Middleware/CheckForMaintenanceMode.php:48
 41. Fisharebest\Webtrees\Http\Middleware\CheckForMaintenanceMode->handle() /index.php:142
 42. {closure}() /index.php:159

**Comment by curtisdelicata** [comment]
In chart.phtml

options must be replaced with values

**Comment by magicsunday** [comment]
Thanks. Fixed with https://github.com/magicsunday/webtrees-fan-chart/commit/406f7482b4cd004bf4d013f24e11352fa5f6bb7c
