### ISSUE TITLE
v1.7 - birthdate is displayed as death date on Safari-Browser (MacOSX and iOS)

### ISSUE THREAD

**Issue by HonkXL** [magicsunday/webtrees-fan-chart#29]
I just installed webtrees-fan-chart into my webtrees 1.7.14 installation. It's running on PHP 7.3.

My father is born in 1940, my mother in 1948, but in the graphic it looks like they died in this year. The text should be 1940-  and 1948-  and not -1940 and -1948.

<img width="716" alt="faecher-webtrees" src="https://user-images.githubusercontent.com/16715040/60547192-6117af80-9d1f-11e9-9b7b-1a597660e80d.png">

**Comment by kiwi3685** [comment]
I'm not convinced this is an issue with the fan-chart code. It uses the same function for birth-death timespan of **every** individual, and your image shows that your own birth is displayed correctly.

(function is:
getTimeSpan(t){return t.data.born||t.data.died?t.data.born+"-"+t.data.died:null}
)

Double-check your data?

**Comment by HonkXL** [comment]
No, ist is an Isle of webtrees-Fan-Chart.

Here the same from the Original Fan Chart, where the dates are ok:

![46F20142-617F-403A-843E-BFA9FB1EDEB4](https://user-images.githubusercontent.com/16715040/60564866-9ba23c00-9d61-11e9-8c94-73af271f8dbe.png)

**Comment by HonkXL** [comment]
I just checked it with PHP 7.1.8 and 7.3.6 with same result.

**Comment by magicsunday** [comment]
What version of the fan chart did you install? Did you use `composer require magicsunday/webtrees-fan-chart --update-no-dev` to install the module? I have no problems with PHP 7.1.30 on my server.

**Comment by HonkXL** [comment]
I downloaded the 1.7.1 zip file and uploaded it to the modules_v3 folder.

**Comment by HonkXL** [comment]
I deleted the modules_v3/ancestral-fan-chart folder ,removed the settings one the module page of webtrees and then I uploaded modeles_v3/webtrees-fan-chart from the latest ZIP-file to the server and activated it in the settings. Same problem.
Sorry that I do not use composer - never used this before for anything.

**Comment by HonkXL** [comment]
I just tried it again - it seems to be a problem on Safari browsers only! I can reproduce it on Safari for Mac OSX and Safari on Apple iPhone and iPad. It works fine in Firefox or Chrome on MacOS.

**Comment by magicsunday** [comment]
Hm, it seems to be a problem with the css styles "direction" and "unicode-bidi".

**Comment by HonkXL** [comment]
I tried it out and found a solution!
In the file webtrees-fan-chart.css there is this class:

starting on line 68 there is this part:

```
#page-fan svg .label .date {
    fill: #7f7f7f;
    font-weight: normal;
    direction: ltr;
    unicode-bidi: plaintext;
}
```

Here I removed this line:

`    unicode-bidi: plaintext;
`

I am not sure if there is an other problem if this line is not present, but it works for me after this change.

**Comment by magicsunday** [comment]
@HonkXL Is this still an issue for you with the latest version from master branch? On my iPad I could not reproduce this.

**Comment by HonkXL** [comment]
Yes, works now with the latest version!
