### ISSUE TITLE
Error with webtrees 2.0

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-fan-chart#30]
I try your module using webtrees 2.0 and i have this error:

> Fatal error: Declaration of MagicSunday\Webtrees\FanChart\Traits\UtilityTrait::boot(Fisharebest\Webtrees\Module\ModuleThemeInterface $theme): void must be compatible with Fisharebest\Webtrees\Module\FanChartModule::boot(): void in ........\htdocs\webtrees\modules_v4\webtrees-fan-chart\src\Module.php on line 30

Thanks

**Comment by magicsunday** [comment]
Due the massive changes in webtrees 2.0 it was a bit of work, but hopefully I got it fixed. Could you please try the latest master version?

**Comment by Fa10175** [comment]
I just test it and i work for me 
Thanks
