### ISSUE TITLE
Not working - Webtrees 2.0

### ISSUE THREAD

**Issue by gregkuhnert** [magicsunday/webtrees-fan-chart#31]
Not working...

> Fatal error: Class MagicSunday\Webtrees\AncestralFanChart\Module contains 6 abstract methods and must therefore be declared abstract or implement the remaining methods (Fisharebest\Webtrees\Module\ModuleChartInterface::chartBoxMenu, Fisharebest\Webtrees\Module\ModuleChartInterface::chartMenu, Fisharebest\Webtrees\Module\ModuleChartInterface::chartMenuClass, ...) in /home/.sites/123/site64/web/modules_v4/webtrees-fan-chart/src/Module.php on line 24

**Comment by magicsunday** [comment]
See #30

**Comment by gregkuhnert** [comment]
Yes. Working. Could you consider a new release ZIP file - Your instructions give three methods for install. I notice the ZIP file is quite old.
