### ISSUE TITLE
Name change does not work

### ISSUE THREAD

**Issue by gregkuhnert** [magicsunday/webtrees-fan-chart#32]
Using Webtrees 2.0, if you go to an individual, and then try to change the name using the pull down menu, it fails to go to the new individual. I saw #5 as a previous fix in 1.7, but this is broken in 2.x

**Comment by Gunnar-GO** [comment]
i wanted to post the same, is i just seconding the bug.

**Comment by TheRealJPS** [comment]
same here

**Comment by magicsunday** [comment]
Should be fixed in master now.

**Comment by TheRealJPS** [comment]
> 
> 
> Should be fixed in master now.

The name change works fine now, however, no diagram is shown, Tested with webtrees 2.0.2 with php 7.4 and 7.3. I tried Firefox, Chrome, Opera and Edge Browser, Cache was cleared.
[See here...](https://ahnen.familie-stern.de/tree/stern/webtrees-fan-chart/I1?generations=6&fanDegree=210&hideEmptySegments=0&showColorGradients=0&innerArcs=4&fontScale=100)

**Comment by TheRealJPS** [comment]
> 
> 
> > Should be fixed in master now.
> 
> The name change works fine now, however, no diagram is shown, Tested with webtrees 2.0.2 with php 7.4 and 7.3. I tried Firefox, Chrome, Opera and Edge Browser, Cache was cleared.

Fixed with the latest master from today, thanks.
