### ISSUE TITLE
underline primary name

### ISSUE THREAD

**Issue by Gunnar-GO** [magicsunday/webtrees-fan-chart#33]
In the whole rest of webtrees the primary name / nickname ist underlined.

It would be a nice to take the feature over to the fan-chart.

**Comment by jpretired** [comment]
> In the whole rest of webtrees the primary name / nickname ist underlined.
There are no underlined names in my webtrees site. Where do you set to underline them?

**Comment by Gunnar-GO** [comment]
the mainly/primary (don't know the english equivalent, in german Rufname) is underlined. It's the name the person uses / reacts to.

You can define this by write an * behind the name

Maria Luise --> Maria* Luise -> Maria is underlined.

**Comment by jpretired** [comment]
Understand, thank you.

**Comment by magicsunday** [comment]
Depends on https://github.com/fisharebest/webtrees/pull/3096

**Comment by magicsunday** [comment]
Added with 88fbea16030919f93fcf125e72ffce0e7fb3fc7c
