### ISSUE TITLE
no fan chart displayed

### ISSUE THREAD

**Issue by jpretired** [magicsunday/webtrees-fan-chart#36]
latest master with webtrees 2.0.3-dev and php both 7.2 and 7.3 no fan chart displayed, no error.

**Comment by dbq-andersons** [comment]
I'm seeing the same.  PHP 7.2.  The module works, but no chart is displayed.

**Comment by magicsunday** [comment]
Strange. I use latest master of webtrees (2.0.3-dev) and PHP 7.2 too. I can see the chart on my system.

**Comment by dbq-andersons** [comment]
Nothing in the Apache error log (both FireFox and Chrome browsers).  Here's the access log entry:

`204.69.146.61 - - [25/Feb/2020:11:06:43 -0600] "GET /genealogy/webtrees2-test/tree/scrubbed-tree HTTP/1.1" 200 6611 "https://www.dbq-andersons.com/genealogy/webtrees2-test/tree/scrubbed-tree/webtrees-fan-chart/I10?generations=4&fanDegree=180&hideEmptySegments=0&showColorGradients=0&innerArcs=4&fontScale=100" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36"`

Feel free to poke around my test site: https://www.dbq-andersons.com/genealogy/webtrees2-test/ and see if the error reproduces for you. Yours is the only fan chart active right now on that site.

Bill

**Comment by Gunnar-GO** [comment]
for me its working fine 

WT 2.0.2 /PHP7.3.9

**Comment by dbq-andersons** [comment]
Are there any "special" PHP extensions needed for this module?  That's what it feels like to me at this point.  jpretired and I are missing something on our sites that you two are not.

Thanks,
Bill

**Comment by Gunnar-GO** [comment]
Don't know, the php config of my ISP is pretty much lower standard.

I just moved the folder and extracted the new one to modules_v4, maybe some is mixed in your copy ?

**Comment by magicsunday** [comment]
Should fixed now. Webtrees 2.0 changed the way CSS/JS files are included by modules. This fact was still missing.

**Comment by jpretired** [comment]
Fixed indeed! Thank you!

**Comment by dbq-andersons** [comment]
Fixed for me as well.  Thanks!

**Comment by TheRealJPS** [comment]
Fixed here as well, thanks.
