### ISSUE TITLE
Save options

### ISSUE THREAD

**Issue by Gunnar-GO** [magicsunday/webtrees-fan-chart#37]
Another idea for enhance would be 

save the setted options, so 
generations, empty segments, view / degree, inner circle ... 
would be the same and must not every time again set.

:)

**Comment by jpretired** [comment]
I support this good idea.

**Comment by magicsunday** [comment]
Please take a look at the current version from the master branch. This includes to local storage part.

**Comment by jpretired** [comment]
As to me works OK. Tested with firefox and chromium.
Thank you.

**Comment by jpretired** [comment]
But see issue #39 !
