### ISSUE TITLE
Individual name in fan chart

### ISSUE THREAD

**Issue by jpretired** [magicsunday/webtrees-fan-chart#39]
With the last version od this addon there is a new issue:
The individual name is taken from given name + surname whereas it should be taken from name, i.e. from Name /Surname/

**Comment by magicsunday** [comment]
I don't get the point. Could you please explain a little more? May be you could also add a screenshot to explain the problem in more detail.

**Comment by jpretired** [comment]
In Czech language the females' surnames are subject to gender inflection, i.e. the father's or husband's (family) surname is inflected.

Example:
**Individual page:**

![Výběr_055](https://user-images.githubusercontent.com/350656/76152761-e4b24900-60c3-11ea-8f9b-f0892c763719.jpg)
![Výběr_053](https://user-images.githubusercontent.com/350656/76152748-a61c8e80-60c3-11ea-9819-25640e1b2f16.jpg)

**GEDCOM**:
![Výběr_054](https://user-images.githubusercontent.com/350656/76152755-bf253f80-60c3-11ea-8e8a-30cc0da22257.jpg)

**Fan chart:**
![Výběr_055](https://user-images.githubusercontent.com/350656/76152769-f0057480-60c3-11ea-81cb-8d76e3636227.jpg)

**Comment by magicsunday** [comment]
@jpretired Could you please test the latest version from master. I changed the way of extracting the name parts.

**Comment by jpretired** [comment]
Tested - now it is OK. Thank you very much.
By the way, so it was in your fan chart for webtrees 1.7:
`    private function getIndividualData(Individual $person, $generation)
    {
        $fullName        = Filter::unescapeHtml($person->getFullName());
        $alternativeName = Filter::unescapeHtml($person->getAddName());

        return array(
            'id'              => 0,
            'xref'            => $person->getXref(),
            'generation'      => $generation,
            'name'            => $fullName,
            'alternativeName' => $alternativeName,
            'isAltRtl'        => $this->isRtl($alternativeName),
            'sex'             => $person->getSex(),
            'born'            => $person->getBirthYear(),
            'died'            => $person->getDeathYear(),
            'color'           => $this->getColor($person),
            'colors'          => [[], []],
        );
    }
`

**Comment by magicsunday** [comment]
Yes, now it is a little bit more complicated in order to highlight the preferred name of an individual.
