### ISSUE TITLE
Zoom problem in Firefox v71.0 and higher

### ISSUE THREAD

**Issue by TheDutchJewel** [magicsunday/webtrees-fan-chart#40]
There's a problem with webtrees-fan-chart v1.7.1 and zooming: in any Firefox version before v71.0, zooming works fine, but in Firefox v71.0 and higher, each zoom results in hidden text in the first five generations.
You can check it yourself with a portable version of Firefox, like:
- [Mozilla Firefox v70.0.1](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2070.0.1/): no zoom problem
- [Mozilla Firefox v71.0](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2071.0/): zoom problem
- [Mozilla Firefox v74.0](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2074.0/): zoom problem

You can check it with Ctrl+Scroll, or simply change the Firefox window size by double clicking in the header, which switches from window to full screen and vice versa.

Is it possible to fix this nasty problem?

**Comment by magicsunday** [comment]
Sound exactly like the problem as described in #38 

A possible fix would be to upgrade to webtrees 2.0 and use the latest 2.0 release of the module. Is this possible for you?

**Comment by TheDutchJewel** [comment]
Tested webtrees-fan-chart v2.0 with webtrees v2.0.2: zoom works fine!

**Comment by TheDutchJewel** [comment]
It works for webtrees 2.0, but is there also a fix for webtrees 1.7.16?

webtrees 1.7.16 has the advantage that on the 'Facts and Events' pages all sources and notes are collapsed by default and can be expanded separately. A solution for that version would therefore be welcome.

**Comment by magicsunday** [comment]
Should be fixed in v1.7.2
