### ISSUE TITLE
Reset function in v2.0 doesn't work

### ISSUE THREAD

**Issue by TheDutchJewel** [magicsunday/webtrees-fan-chart#42]
If I click on the reset function in webtrees-fan-chart v2.0, nothing happens.

If I click on the reset button in webtrees-fan-chart v1.7.2, it reset the changes before if I haven't pressed the view button. But in v2.0 it doesn't do anything.

**Comment by magicsunday** [comment]
The reset button currently only resets the chart if it was zoomed or moved around. The button will be removed or renamed in a future release to reflect this behaviour.

**Comment by magicsunday** [comment]
Button has now be renamed in order to reflect its current behaviour
