### ISSUE TITLE
Interpretation of individuals without a date as deceased

### ISSUE THREAD

**Issue by TheRealJPS** [magicsunday/webtrees-fan-chart#43]
Perhaps this is a feature but I find it unfortunate that individuals who do not have birth and funeral dates are now shown as deceased...
![grafik](https://user-images.githubusercontent.com/50000131/77236521-99b62c80-6bbf-11ea-9085-7016be248c28.png)

**Comment by magicsunday** [comment]
Oh, it shouldn't be that way.

**Comment by magicsunday** [comment]
Could you please test again with the latest master version to verify the problem is gone?

**Comment by TheRealJPS** [comment]
> 
> 
> Could you please test again with the latest master version to verify the problem is gone?

Great, thanks a lot! ...

![grafik](https://user-images.githubusercontent.com/50000131/77251210-64582000-6c4d-11ea-900b-ff2681c88eb1.png)
