### ISSUE TITLE
Adding Czech translation

### ISSUE THREAD

**Issue by jpretired** [magicsunday/webtrees-fan-chart#47]
May I ask for adding Czech translation of webtrees-fan-chart.
The .mo and .po should be put into /lang/cs folder.

[Czech-mo-po.zip](https://github.com/magicsunday/webtrees-fan-chart/files/4624395/Czech-mo-po.zip)

**Comment by magicsunday** [comment]
Yes for sure. Thanks!

Add with 891407abb3b71f39c460759debd0f381d71bfb2e
