### ISSUE TITLE
Language for Vietnamese

### ISSUE THREAD

**Issue by ngohuuthuan** [magicsunday/webtrees-fan-chart#50]
Thank you for creating this module, Can you give me a Vietnamese version?

**Comment by magicsunday** [comment]
I don't speak Vietnamese myself. Please create a language file with the corresponding ISO language code for the desired language. Then create a pull request and add these files so that I can add them to the repository.

**Comment by ngohuuthuan** [comment]
Thank you for replying!
I use poedit and have created Vietnamese language file.
Wish you good health and create many useful modules!
[lang_vi.zip](https://github.com/magicsunday/webtrees-fan-chart/files/4879422/lang_vi.zip)

**Comment by magicsunday** [comment]
Thank you.
