### ISSUE TITLE
Adding translation

### ISSUE THREAD

**Issue by fragolan** [magicsunday/webtrees-fan-chart#52]
Hi there, 
I realy like the way you changed Fan chart module. I tried to add translation to my language Serbian by creating directory named sr with two files, but it didn't worked... Do you have any ideas what could be the problem

**Comment by magicsunday** [comment]
The translations are structured in two files. A `po`-file with the translations (human readable). These are converted into a `mo`-file (binary) by a suitable program. The files must be named `messages.po` and `messages.mo`. For translating/converting you can use PoEdit (https://poedit.net/) for instance.

Alternatively, you can create a new pull request with your translation file (* .po) or send it to me by email so I can add it to the repository. Then everyone benefits from it. Others have already done this, this way.

**Comment by fragolan** [comment]
Well, actually I did it on that way. I use PoEdit for translation, but from some reason it doesn't work. I'm not sure is it problem with folder names or some language identification in file. In webtrees Serbian cyrilic folder is named "sr" and for Serbian Latin folder is named "Sr-Latn". By unicode, these languages are sr-RS and sr-YU.
I tried almost everything with names but still no sollution.

**Comment by magicsunday** [comment]
If you send me the file, I can take a look at it too.

**Comment by fragolan** [comment]
Here is the files, both latin and cyrilic version of Serbian language translation... Thanx in advance
[sr.zip](https://github.com/magicsunday/webtrees-fan-chart/files/5618179/sr.zip)

**Comment by magicsunday** [comment]
Thanks for you contribution. I added the language files and changed the language of my webtrees installation to serbian and all labels gets displayed in serbian language.
