### ISSUE TITLE
Text displayed over each other

### ISSUE THREAD

**Issue by carolalind** [magicsunday/webtrees-fan-chart#55]
text are show on top of each other on chart in firefox developer ediotion.

https://ann-britt.se/tree/Ann-Britt%27s%20Anor/webtrees-fan-chart/I4709

https://ann-britt.se/temp/fan-chart.png

**Comment by magicsunday** [comment]
Seems like a bug in the developer edition. I could not replicate the bug in the normal Firefox, Chrome and Edge and other browsers (iPad) also do not show this behaviour.

**Comment by carolalind** [comment]
Ok.

Something I should report to them instead perhaps?

Thanks for your reply!

Regards,

Carola Lind

________________________________
Från: Rico Sonntag <notifications@github.com>
Skickat: Tuesday, January 5, 2021 4:38:25 PM
Till: magicsunday/webtrees-fan-chart <webtrees-fan-chart@noreply.github.com>
Kopia: carolalind <carola.lind@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [magicsunday/webtrees-fan-chart] Text displayed over each other (#55)


Seems like a bug in the developer edition. I could not replicate the bug in the normal Firefox, Chrome and Edge and other browsers (iPad) also do not show this behaviour.

**Comment by magicsunday** [comment]
Firefox 85 should be released around end of january. I will leave this ticket open and look at it again.

**Comment by magicsunday** [comment]
Did you already encounter this problem in any previous release of the developer edition?

**Comment by carolalind** [comment]
Ok. I’ll wait and see what happens in ffd85.

No I have never seen this before in ffd but i don’t check this site myself very often since it’s an in memorian site. I only do the updates when they are released.

________________________________
Från: Rico Sonntag <notifications@github.com>
Skickat: Tuesday, January 5, 2021 7:09:58 PM
Till: magicsunday/webtrees-fan-chart <webtrees-fan-chart@noreply.github.com>
Kopia: carolalind <carola.lind@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [magicsunday/webtrees-fan-chart] Text displayed over each other (#55)


Did you already encounter this problem in any previous release of the developer edition?

**Comment by magicsunday** [comment]
OK FF85 is released and the chart looks weird.

**Comment by carolalind** [comment]
Wonder what causes it? Any ideas?

________________________________
Från: Rico Sonntag <notifications@github.com>
Skickat: Friday, January 29, 2021 6:37:01 PM
Till: magicsunday/webtrees-fan-chart <webtrees-fan-chart@noreply.github.com>
Kopia: carolalind <carola.lind@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [magicsunday/webtrees-fan-chart] Text displayed over each other (#55)


OK FF85 is released and the chart looks weird.

**Comment by magicsunday** [comment]
I made a quickfix for now.

**Comment by carolalind** [comment]
Ok will try it tomorrow 🙂

________________________________
Från: Rico Sonntag <notifications@github.com>
Skickat: Friday, January 29, 2021 7:01:33 PM
Till: magicsunday/webtrees-fan-chart <webtrees-fan-chart@noreply.github.com>
Kopia: carolalind <carola.lind@hotmail.com>; Author <author@noreply.github.com>
Ämne: Re: [magicsunday/webtrees-fan-chart] Text displayed over each other (#55)


I made a quickfix for now in the master branch.

**Comment by magicsunday** [comment]
I filed a bug report at mozilla. Lets see what they comment on it: https://bugzilla.mozilla.org/show_bug.cgi?id=1689799

**Comment by magicsunday** [comment]
Should be fixed with Firefox 87.

**Comment by magicsunday** [comment]
FF 87 is out. I reverted the workaround.
