### ISSUE TITLE
Reverse the logic keeping the first letter of names

### ISSUE THREAD

**Issue by SodanWT** [magicsunday/webtrees-fan-chart#60]
Hi,

Is it possible to reverse the logic that keeps only the first letter of the first names when there is not enough space?

I have a lot of individuals that have several first names, the first one being the one with which they're known.
For instance : Pierre Jean Marie Henry Charles DUPOND is displayed P. J. M. H. Charles DUPOND, but should be Pierre J. M. H. C. DUPOND as he was commonly simply called Pierre DUPOND.

Regards,

**Comment by magicsunday** [comment]
You could mark the preferred name of an individual with an asterix in webtrees. Those preferred name is the last one which gets truncated.

In your case, change the name to: Pierre* Jean Marie Henry Charles DUPOND

**Comment by SodanWT** [comment]
Well, I don't think the asterisk should be used systematically. As stated in webtrees "If an individual was not known by their first given name, the preferred name should be indicated with an asterisk: John Paul* /Smith/", so I use it only in this case, which is rare.
Maybe could you add an option or parameter to achieve this, for those using webtrees the same way as I do? Or, as an alternative, could you guide me on what to change so I could make a patch?

**Comment by JustCarmen** [comment]
I agree with SodanWT. The first name listed is the name one is commonly called with and should be the default. I see it happen with my own name in the middle. No one knows me by my second or third given name, but those are written in full while my first name is truncated to 1 letter. It is not common practice to set the first name as preferred name with an asterix, since that is normally the default.

**Comment by magicsunday** [comment]
Ok, so the first given name (if more than one) should be the last one which gets truncated, if no other given name was marked as preferred?

**Comment by SodanWT** [comment]
Yes, that's it. Thanks 😀

**Comment by magicsunday** [comment]
@SodanWT 

I had got some time to look at it again. I used a slightly different approach than you. May you take a look at it, whether this fixes your problem in the right way?

**Comment by SodanWT** [comment]
Hi Rico,
Your fix looks good! Thank you for taking the time to do it :)
