### ISSUE TITLE
Surnames truncated in outer generations

### ISSUE THREAD

**Issue by reteP-riS** [magicsunday/webtrees-fan-chart#66]
With version 2.2.0 I observe several individuals in generation 8, 9 and 10 where the surname is being abbreviated either instead of the last firstname or additionally to the last firstname being abbreviated. This seems to occur regardless of whether a preferred first name exists or not. Everything looks ok for generation 7 and lower. I can't test beyond generation 10. Examples:

- Mary Kathy F. instead of Mary K. Foxtrot
- Susanna K. G. instead of Susanna K. Golf

**Comment by magicsunday** [comment]
Last names are now truncated last.

The fan diagram is limited to 10 generations, as there would no longer be enough space in an 11th generation for the names to be displayed.

**Comment by reteP-riS** [comment]
I only downloaded ./webtrees-fan-chart/resources/js/fan-chart.min.js to test the fix and the issue seems to be resolved. Unfortunately now the birth, marriage and death symbols ∗, ⚭ and † are replaced by a question mark. Is that a new issue or should I wait for a new release to get the full package of changes?

Thank you anyway. Excellent module!

**Comment by magicsunday** [comment]
This is strange, it does not happen in my test environment.

**Comment by reteP-riS** [comment]
The new issue with the birth, marriage and death symbols ∗, ⚭ and † being replaced by a question mark exists on different browsers. So I think that I need to get the full package of changes. It would be very much appreciated if you could create a new release.

**Comment by reteP-riS** [comment]
That new issue is resolved now. Something had gone wrong with the file format when I copied ./webtrees-fan-chart/resources/js/fan-chart.min.js. Thanks again!
