### ISSUE TITLE
Wrong date of marriage

### ISSUE THREAD

**Issue by HRN65** [magicsunday/webtrees-fan-chart#67]
If one of the parents have been married more than once, only first date of marriage is displayed when right clicking.
Because of this, wrong date is displayed for one of the parents of a child.

**Comment by magicsunday** [comment]
So its would be better to hide the marriage date inside the popup?

**Comment by magicsunday** [comment]
Could not reproduze. If this still occurs please re-open this issue and provide more detailed information about the problem.
