### ISSUE TITLE
JSON-THROW-ON-ERROR

### ISSUE THREAD

**Issue by benetel** [magicsunday/webtrees-fan-chart#72]
Hi,
I use Webtrees 2.0.16
As I activate the the pedigree chart custom module (v 2.2.0) and try to display it on my webtrees pages, the resuls is an error message :

"use of undefined constant JSON-THROW-ON-ERROR,
as shown in the image

![image](https://user-images.githubusercontent.com/90130251/132120045-a793b3f1-81c2-4022-9d4b-082c6a43ec2c.png)

**Comment by magicsunday** [comment]
JSON_THROW_ON_ERROR requires at least PHP 7.3. What version do you use?

**Comment by benetel** [comment]
Hello, my provider uses PHP 7.1.3

so it all makes sense, thanks for the answer

**Comment by magicsunday** [comment]
This should be fixed with the latest release. Please note that release 2.2.1 is the last release for PHP < 7.4. I recommend you to upgrade your PHP version as 7.1 is already outdated.

Could you please check if https://github.com/magicsunday/webtrees-fan-chart/releases/tag/2.2.1 is working for you?

**Comment by benetel** [comment]
It works ! Thank you for your work!!
I will meanwhile contact my provider to upgrade my version of PHP.

Best regards,
Nathalie

*Mes racines en Vénétie* : http://www.venarbol.net
*fil de veille sur la généalogie italienne* :
https://www.facebook.com/GenealItalie/


Le lun. 20 sept. 2021 à 12:29, Rico Sonntag ***@***.***> a
écrit :
