### ISSUE TITLE
The names in the inner circles are not broken.

### ISSUE THREAD

**Issue by arbor95** [magicsunday/webtrees-fan-chart#75]
![2021-11-25 10_41_43-Window](https://user-images.githubusercontent.com/6124739/143417677-46fc9c1d-1fbb-48a5-8fba-824e38b4e6e8.jpg)
Die Namen in den inneren Kreisen werden nicht umgebrochen.

**Comment by Gunnar-GO** [comment]
Dieser Fehler tritt bei mir (2.2.1; wt 2.0.17) nicht auf.

**Comment by arbor95** [comment]
Vielleicht ein Problem des Zeilenumbruchs zwischen Windows und Linux?

**Comment by arbor95** [comment]
Das Verhalten ist seit Version 2.2.0 fehlerhaft. Die Version vorher funktioniert bei mir auch.

**Comment by BertKoor** [comment]
Also reported on the webtrees forum:
https://www.webtrees.net/index.php/en/forum/4-customising/36308-pizza-graphic-pedigree-chart-by-magicsunday-current-release-1-2-6#88447

**Comment by magicsunday** [comment]
Please provide more information. What version of the module and webtrees you are using?

**Comment by arbor95** [comment]
sure always using the latest versions. error is since version 2.2.0 of your module.
yesterday switched to webtrees 2.0.19 .
today tried again with 2.2.1 of your module.
the error is still there.

**Comment by arbor95** [comment]
The exported svg, is wrong.
opened with inkscape, you see attached
![2021-12-06 11_34_07-Window](https://user-images.githubusercontent.com/6124739/144831326-b040a22b-68e7-4328-b6fc-7480a6a76f09.jpg)
:

**Comment by arbor95** [comment]
![2021-12-06 11_38_36-Window](https://user-images.githubusercontent.com/6124739/144832383-e68e0f96-dd7b-45fb-86bb-cfb971441b2b.jpg)
from far away like that

**Comment by magicsunday** [comment]
Does the error also occur of you hide the marriage dates?

**Comment by HRN65** [comment]
I see this error in Chrome and Edge. In Firefox everything looks fine.
Hiding the marriage dates makes no difference

**Comment by arbor95** [comment]
yes, it does (as I wrote in previous comment: independant from setting of presentation attributes checkboxes of fan-chart)

I did'nt check firefox, normally I'm using chrome.
But on my mobile device (a samsung with chrome) it is the same error.

**Comment by magicsunday** [comment]
Seems like a bug in Chrome and Edge or an feature of the upcoming SVG 2 standard what Firefox implements.

**Comment by arbor95** [comment]
Das kann ja wohl nicht sein, einen bestehenden Fehler einfach zu ignorieren, wo sogar das exportierte svg im inkscape fehlerhaft angezeigt wird , und die Versionen vor 2.2.0  im Chrome etc eine korrekte Anzeige hatten.

**Comment by mpwt** [comment]
Könnte es sein, dass die ZIP-Datei für v2.2.1 nicht alle Dateien enthält? Mit dem aktuellen Commit wird eine Datei geändert, welche nicht in der ZIP-Datei enthalten ist.

**Comment by arbor95** [comment]
Danach lief gar nichts mehr.
Dann habe ich den kompletten Master verwendet.
Jetzt ist alles im grünen Bereich.
Danke mpwt !!!

**Comment by arbor95** [comment]
Etwas zu früh gefreut: Jetzt tut die Schaltfläche "Weitere Optionen nicht mehr"!

**Comment by mpwt** [comment]
Ich habe auf meiner Seite (https://ffp.bauschaffen.de/tree/Pannier/webtrees-fan-chart/I1) die v2.2.1 mit der einen geänderten Datei fan-chart.min.js laufen und mit Chrome auf dem Tablet funktioniert es aus meiner Sicht bisher. Gern kannst Du das dort mit Deinem Browser probieren.

**Comment by ekdahl** [comment]
I have the same problem, More options... does nothing. Using latest revision from master:
http://solhaga.noip.me/webtrees/tree/Ekdahl-Klahr/webtrees-fan-chart/123
It works when trying your page.

**Comment by magicsunday** [comment]
Branch 2.1 => Upcoming webtrees 2.1
Branch 2.0 => webtrees 2.0

**Comment by magicsunday** [comment]
> Das kann ja wohl nicht sein, einen bestehenden Fehler einfach zu ignorieren, wo sogar das exportierte svg im inkscape fehlerhaft angezeigt wird , und die Versionen vor 2.2.0 im Chrome etc eine korrekte Anzeige hatten.

Sie dürfen sich gerne einbringen und Verbesserung/Bugfixes beisteuern. Mein Tag hat auch nur 24h und meine Freizeit noch viel weniger.

**Comment by magicsunday** [comment]
Export as SVG is broken in 2.1 as Inkscape did not support CSS variables which are now used in webtrees => https://gitlab.com/inkscape/inbox/-/issues/1180

**Comment by arbor95** [comment]
@mpwt : Dann lass mir doch mal eine Kopie von deinem installierten webtrees-fan-chart zukommen. Das sieht auch auf meinem Gerät ok aus. (arbor95@gmx.de)

**Comment by arbor95** [comment]
Mit dem update von 13:38 tut nun auch die Schaltfläche für die Optionen (wieder).
Warum nicht gleich so? Das verlängert auch meine 24 Stunden!

**Comment by ekdahl** [comment]
Thanks @magicsunday, it works after switching to 2.0 branch. I missed that there was a 2.0 branch.

**Comment by mpwt** [comment]
Let's wait for version 2.2.2. Many thanks to magicsunday.
