### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by Fa10175** [magicsunday/webtrees-fan-chart#88]
i give you for french a new messages.po
i had some french traduction to 
#: resources/views/chart.phtml:105
msgid "Show parent marriage dates"
msgstr "Afficher les dates de mariage des parents"
#: resources/views/chart.phtml:160
msgid "Show more options"
msgstr "Afficher les options"
#: resources/views/chart.phtml:161
msgid "Hide more options"
msgstr "Masquer les options"

[messages.po.txt](https://github.com/magicsunday/webtrees-fan-chart/files/10384158/messages.po.txt)

**Comment by magicsunday** [comment]
Merci.
