### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by rbb-soft** [magicsunday/webtrees-fan-chart#94]
when i try to install i got this error:

Fatal error: Declaration of MagicSunday\Webtrees\Composer\ModuleInstaller::supports(string $packageType): bool must be compatible with Composer\Installer\LibraryInstaller::supports($packageType) in C:\xampp8\htdocs\webtree\vendor\magicsunday\webtrees-module-installer-plugin\src\Composer\ModuleInstaller.php on line 60
**Expected behavior**

use this script install:

composer require magicsunday/webtrees-fan-chart:* --update-no-dev

**Comment by magicsunday** [comment]
- What PHP version do you use?

**Comment by rbb-soft** [comment]
> * What PHP version do you use?
> 
>     * What webtrees version?

PHP 8.1.17

webtree lasted

**Comment by magicsunday** [comment]
Strange. Could you please try intallation using:

`composer require magicsunday/webtrees-fan-chart:dev-master --update-no-dev`

**Comment by rbb-soft** [comment]
Work thanks

**Comment by rbb-soft** [comment]
Works thanks
